### ISSUE TITLE
 FILEPROPERTY() Not supported in babelfish

### ISSUE THREAD

**Issue by Aravind2601** [bill-ramos-rmoswi/babelfish_postgresql_towel#2]
@bill-ramos-rmoswi 
we have the below procedure in T-SQL which use the **FILEPROPERTY()**  to get the size of db files from **sys.master_files table**  . Since it not supported in Babel fish we created helper function to get the size but getting different size.
T-SQL:
![image](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/126471258/5d965abc-87f4-46c6-9414-04c67dd92b33) 
Sys.master_files:
![image](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/126471258/caad8470-7254-45f4-8173-fda61f5f5599)

Helper function:
-- FUNCTION: master_dbo.get_dbsize(text)

-- DROP FUNCTION IF EXISTS master_dbo.get_dbsize(text);

CREATE OR REPLACE FUNCTION master_dbo.get_dbsize(
	sch_name text)
    RETURNS int
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
BEGIN
     Return (sum(pg_relation_size(quote_ident(schemaname) || '.' || quote_ident(tablename)))::int) FROM pg_tables 
WHERE schemaname Like sch_name || '%';
END;
$BODY$;

ALTER FUNCTION master_dbo.get_dbsize(text)
    OWNER TO wilton;

Babelfish:
![image](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/126471258/aba63665-8f46-43e3-9e6a-5c6420331db9)

Question : How to get the size of postgreSQL database equivalent to SQL ? It seems when we use the existing methods in PostgreSQL, there is mismatch between the sizes between SQL and PostgreSQL.

**Comment by bill-ramos-rmoswi** [comment]
Hi @Aravind2601,
There are substantial differences between storage methods with SQL Server and PostgreSQL. I used Claude 3.5 Sonnet chat with the following prompt for this answer. The response meets my sniff test in terms of accuracy.

Prompt:
```
What are the key differences between the way that SQL Server stores data in LOG and    

DATA files versus PostgreSQL that I can explain to my DBA team. Also include how to    

compare the size of databases on disk using SQL Server and PostgreSQL with specific  
  
examples. Include reference links to source material so they can learn more about it.   
```

# Key differences in storage between SQL Server and PostgreSQL
Certainly, I'll explain the key differences between SQL Server and PostgreSQL data storage, and provide examples for comparing database sizes. Here's a detailed comparison:

1. Data Storage Structure:

SQL Server:
- Uses two main file types: .mdf (primary data file) and .ldf (transaction log file).
- Can have secondary data files (.ndf) for filegroup management.
- Data is organized into 8KB pages, grouped into 64KB extents.

PostgreSQL:
- Uses a directory structure with multiple files.
- Main data is stored in files within the base subdirectory.
- Write-Ahead Logs (WAL) are separate files, similar to SQL Server's transaction logs.
- Default page size is 8KB, but can be configured during compilation.

2. File Management:

SQL Server:
- Manages files at the database level.
- Allows manual placement and growth of data and log files.
- Uses filegroups for data distribution across files.

PostgreSQL:
- Manages files at the tablespace level.
- Each relation (table, index) typically has its own file(s).
- Uses symbolic links for tablespace management.

3. Transaction Logs:

SQL Server:
- Uses a single .ldf file for the transaction log.
- Log file is circular and reuses space after checkpoints.

PostgreSQL:
- Uses multiple WAL (Write-Ahead Log) files.
- WAL files are archived and can be used for point-in-time recovery.

4. Comparing Database Sizes:

SQL Server:
To get the size of all databases:

```sql
SELECT 
    DB_NAME(database_id) AS DatabaseName,
    ROUND(SUM(size * 8.0 / 1024), 2) AS SizeInMB
FROM sys.master_files
GROUP BY database_id
ORDER BY SizeInMB DESC;
```

For a specific database:

```sql
USE YourDatabaseName;
SELECT 
    DB_NAME() AS DatabaseName,
    ROUND(SUM(size * 8.0 / 1024), 2) AS SizeInMB
FROM sys.database_files;
```

PostgreSQL:
To get the size of all databases:

```sql
SELECT 
    datname AS DatabaseName, 
    pg_size_pretty(pg_database_size(datname)) AS Size
FROM pg_database
ORDER BY pg_database_size(datname) DESC;
```

For a specific database:

```sql
SELECT 
    current_database() AS DatabaseName,
    pg_size_pretty(pg_database_size(current_database())) AS Size;
```

5. Key Differences to Highlight:

- File Structure: SQL Server uses fewer, larger files, while PostgreSQL uses many smaller files.
- Tablespaces: Both support tablespaces, but implementation differs.
- Transaction Logs: SQL Server uses a circular log, PostgreSQL uses sequential WAL files.
- Backup Approaches: Different due to file structure differences.
- Page Size: SQL Server is fixed at 8KB, PostgreSQL is configurable.

References for further reading:

1. SQL Server Storage Engine:
   https://learn.microsoft.com/en-us/sql/relational-databases/sql-server-index-design-guide?view=sql-server-ver16

2. PostgreSQL Storage:
   https://www.postgresql.org/docs/current/storage.html

3. SQL Server File Management:
   https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-files-and-filegroups?view=sql-server-ver16

4. PostgreSQL WAL:
   https://www.postgresql.org/docs/current/wal-intro.html

5. SQL Server Database Size:
   https://learn.microsoft.com/en-us/sql/relational-databases/databases/estimate-the-size-of-a-database?view=sql-server-ver16

6. PostgreSQL Database Size:
   https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-DBSIZE

These differences in storage architecture have implications for performance tuning, backup strategies, and overall database management. Understanding these distinctions will help your DBA team optimize their approach for each database system.

### Quick note: What is the problem you are trying to solve?

**Comment by Aravind2601** [comment]
@bill-ramos-rmoswi, we need to find the size of databases but in our case wilton is the database. So when we execute below query it will show the size of wilton, but we need the size of the employee schema.
**Query:** 
SELECT 
    current_database() AS DatabaseName,
    pg_size_pretty(pg_database_size(current_database())) AS Size;

**Comment by Aravind2601** [comment]
@staticlibs thanks Alex . Able to get the size .

**Comment by Aravind2601** [comment]
Got the size of database in postgresql with the help of above given queries
